version: 0.2
env:
  variables:
    AWS_REGION: "us-east-2"
phases:
  pre_build:
    commands:
      - cd terraform/liberty/infra || true
      - terraform init
      - terraform validate
  
  build:
    commands:
      - cd terraform/liberty/infra || true
      - terraform apply --auto-approve
      - terraform output kubectl_config >config
