version: 0.2
env:
  variables:
    AWS_REGION: "us-east-2"
phases:
  pre_build:
    commands:
      - export ACCOUNT_ID=$(aws sts get-caller-identity | grep Account | tr -d '":,' | awk '{print $2}')
      - export CLUSTER="$(eksctl get cluster | grep liberty | awk '{print $1}')"
  
  build:
    commands: |
      echo "CLUSTER: $CLUSTER"
      eksctl delete iamserviceaccount  --cluster "$CLUSTER"  --namespace kube-system  --name aws-load-balancer-controller
      eksctl create iamserviceaccount  --cluster "$CLUSTER"  --namespace kube-system  --name aws-load-balancer-controller  --attach-policy-arn arn:aws:iam::${ACCOUNT_ID}:policy/AWSLoadBalancerControllerIAMPolicy  --override-existing-serviceaccounts  --approve

