version: 0.2
env:
  variables:
    AWS_REGION: "us-east-2"
    LBC_VERSION: "v2.3.0"
phases:
  pre_build:
    commands:
      - export ACCOUNT=$(aws sts get-caller-identity | grep Account | tr -d '":,' | awk '{print $2}')
      - export CLUSTER=$(aws eks list-clusters | grep liberty | tr -d ' "')
      - #OUT=$(aws sts assume-role --role-arn arn:aws:iam::${ACCOUNT}:role/tf-codebuild-role --role-session-name aaa);\
      - #export AWS_ACCESS_KEY_ID=$(echo $OUT | jq -r '.Credentials''.AccessKeyId');\
      - #export AWS_SECRET_ACCESS_KEY=$(echo $OUT | jq -r '.Credentials''.SecretAccessKey');\
      - #export AWS_SESSION_TOKEN=$(echo $OUT | jq -r '.Credentials''.SessionToken');
      - #aws sts get-caller-identity
  build:
    commands:
      - #aws eks --region ${AWS_REGION} update-kubeconfig --name ${CLUSTER} --role-arn arn:aws:iam::${ACCOUNT}:role/tf-codebuild-role
      - aws eks --region ${AWS_REGION} update-kubeconfig --name ${CLUSTER} 
      - cat /root/.kube/config
      - kubectl config get-contexts
      - kubectl get svc  
      - kubectl get nodes  
      - kubectl get sa -n kube-system 
      - kubectl get sa aws-load-balancer-controller -n kube-system -o yaml
      - kubectl apply -k github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master
