version: 0.2
env:
  variables:
    AWS_REGION: "us-east-2"
phases:
  pre_build:
    commands:
      - export ACCOUNT=$(aws sts get-caller-identity | grep Account | tr -d '":,' | awk '{print $2}')
      - cd teraform/liberty/infra
      - CLUSTER=$(aws eks list-clusters | grep liberty | tr -d ' "')
  build:
    commands:
      - aws eks --region ${AWS_REGION} update-kubeconfig --name ${CLUSTER} --role-arn arn:aws:iam::${ACCOUNT}:role/tf-codebuild-role
      - cat /root/.kube/config
      - kubectl config get-contexts
      - kubectl get svc  
      - kubectl get nodes  
      - kubectl get sa -n kube-system 
      - kubectl get sa aws-load-balancer-controller -n kube-system -o yaml
